[package]
name = "ref-portals"
version = "0.0.0"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"

[dev-dependencies]
assert-impl = "0.1.3"
assert-panic = { path = "../assert-panic" }

[dependencies]
wyz = "0.2.0"
